version: "3"

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./code:/code
    networks:
      - internal
      - proxy
    labels:
      - traefik.frontend.rule=Host:example.aboutbits.local
      - traefik.docker.network=proxy
      - traefik.port=80
      - traefik.backend=example
  php:
    build:
      context: ./php
    volumes:
      - ./code:/code
    networks:
      - internal
    labels:
      - traefik.enable=false

networks:
  proxy:
    external: true
  internal:
    external: false
