version: "3"

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./code:/code
    networks:
      - internal
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.example.entrypoints=http,https
      - traefik.http.routers.example.rule=Host(`example.proxy.test`)
      - traefik.http.routers.example.tls=true
      - traefik.http.routers.example.service=example
      - traefik.http.services.example.loadbalancer.server.port=80
  php:
    build:
      context: ./php
    volumes:
      - ./code:/code
    networks:
      - internal
    labels:
      - traefik.enable=false

networks:
  proxy:
    external: true
  internal:
    external: false
