tls:
  options:
    default:
      minVersion: VersionTLS12
    mintls13:
      minVersion: VersionTLS13

  stores:
    default:
      defaultCertificate:
        certFile: "/certificates/local.crt"
        keyFile: "/certificates/local.key"
